setup: |
  cd matrix && poetry install
  echo "Done installing project dependencies!"
---

# perform checks on a file
- matrix/matrix/main.py:
    - description: Ensure that the main.py file exists in the matrix/matrix/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for main.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Create a sufficient number of docstring (i.e., multiple-line) comments in main.py
      check: CountMultipleLineComments
      options:
        language: "Python"
        count: 6
        exact: false
    - description: Create a sufficient number of single-line comments in main.py
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 8
        exact: false

# perform checks on a file
- matrix/tests/test_matrix.py:
    - description: Ensure that the test_matrix.py file exists in the matrix/tests/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for test_matrix.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Create a sufficient number of docstring (i.e., multiple-line) comments in test_matrix.py
      check: CountMultipleLineComments
      options:
        language: "Python"
        count: 4
        exact: false
    - description: Create a sufficient number of single-line comments in test_matrix.py
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 8
        exact: false

# perform checks on a file
- writing/reflection.md:
    - description: Ensure that the reflection.md file exists in the writing/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for the reflection
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the reflection file
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true
    - description: Confirm that the markdown file has the correct number of headers
      check: CountMarkdownTags
      options:
        tag: heading
        count: 11
        exact: false
    - description: Confirm that the markdown file has the correct number of fenced code blocks
      check: CountMarkdownTags
      options:
        tag: code_block
        count: 3
        exact: false

# run a command
- description: Pass the source code formatting checks run by black
  command: cd matrix && poetry run task black

# run a command
- description: Pass the linting checks run by flake8
  command: cd matrix && poetry run task flake8

# run a command
- description: Pass the import checks run by isort
  command: cd matrix && poetry run task isort

# run a command
- description: Pass the linting checks run by mypy
  command: cd matrix && poetry run task mypy

# run a command
- description: Pass the linting checks run by pydocstyle
  command: cd matrix && poetry run task pydocstyle

# run a command
- description: Pass the linting checks run by pylint
  command: cd matrix && poetry run task pylint

# run a command
- description: Pass the linting checks run by pymarkdown
  command: cd matrix && poetry run task markdownlint

# run the program and confirm correct number of lines in the output
- description: Run the program and confirm the correct number of non-blank lines in the output, using list approach
  check: CountCommandOutput
  options:
    command: 'cd matrix && poetry run matrix --matrix-dir input --matrix-file matrix.txt'
    count: 11
    exact: true

# count number of commits in the GitHub repository
- description: Have at least a specific minimum of commits in repository
  check: CountCommits
  options:
    count: 6
